### ISSUE TITLE
docker 下拉取需要身份验证，怎么验证

### ISSUE THREAD

**Issue by xuanxs** [Python3WebSpider/ProxyPool#103]
docker pull docker.pkg.github.com/python3webspider/proxypool/proxypool:master
Error response from daemon: Head https://docker.pkg.github.com/v2/python3webspider/proxypool/proxypool/manifests/master: no basic auth credentials

**Comment by Germey** [comment]
你用 germey/proxypool，从 Docker Hub 下。
