### ISSUE TITLE
使用docker无法获取代理IP,萌新求助

### ISSUE THREAD

**Issue by 2517577636** [Python3WebSpider/ProxyPool#104]
docker-compose up命令运行后，容器开启。
浏览器输入http://localhost:5555/random地址，无法获取随机IP地址。
出现Internel server error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Germey** [comment]
目前应该是没问题的，如果运行之后很快就打开获取代理，可能是代理还没有抓到报错了，可以稍微等一会。
