### ISSUE TITLE
书上的和这个上面的都试过了就是不行

### ISSUE THREAD

**Issue by guaiguaidashu** [Python3WebSpider/ProxyPool#11]
各个库以及Python的版本都是符合要求的
然后python run.py 的时候就报错
ImportError: cannot import name 'etree' from 'lxml' 
实在是百度不到方法了，求解。

**Comment by caiheyao** [comment]
python3.7会保存,用3.6版本

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
