### ISSUE TITLE
how can i find proxy server

### ISSUE THREAD

**Issue by imhajes** [Python3WebSpider/ProxyPool#113]
how can i run proxy server to used as proxy connect to proxy pool

**Comment by Germey** [comment]
Just use docker.

```
docker-compose up
```

Then just visit http://localhost:5555/random

**Comment by imhajes** [comment]
yes i know that
but how can i use it in my browser as proxy like localhost:5555

**Comment by Germey** [comment]
No, you can't use it for proxy, this is just an endpoint for you to fetch proxy. And it is used for coding not directly used. You should use code to request this endpoint then parse the result to get a proxy. Then use this proxy to do other things.
