### ISSUE TITLE
task exception TypeError('ssl should be SSLContext, bool, Fingerprint or None, got False instead.')

### ISSUE THREAD

**Issue by lycanthropes** [Python3WebSpider/ProxyPool#117]
Task exception was never retrieved future: <Task finished name='Task-27046' coro=<Tester.test() done, defined at tester.py:34> exception=TypeError('ssl should be SSLContext, bool, Fingerprint or None, got False instead.')> Traceback (most recent call last):   File "\proxypool\processors\tester.py", line 40, in test     async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(ssl=False)) as session:   File "\lib\site-packages\aiohttp\connector.py", line 765, in __init__     self._ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)

**To Reproduce**
（1）从github直接下载ProxyPool；
（2）conda 新建env并pip install -r requirements.txt
（3）定位到ProxyPool文件夹位置，在terminal中输入python run.py；
"" Result""
能够正常运行并获取IP，但经常会出现上述test的错误提示。

**Environments (please complete the following information):**
 - OS: [Win10]
 - environment [conda]
 - Python [Python 3.8]

![proxy_bug](https://user-images.githubusercontent.com/38000321/114287610-b8bd8000-9a9a-11eb-9fe4-d83286766053.jpg)

**Comment by Germey** [comment]
现在已经修改成运行我已经 build 好的镜像，请重新试试。
