### ISSUE TITLE
docker只需要要一条命令，那里我卡住了，您是说的那个环境是只有把那两个下载好就可以，还是下载好还需要配置链接什么的，求大神帮助和理解一下小白吧，

### ISSUE THREAD

**Issue by renzhetiandi** [Python3WebSpider/ProxyPool#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. macOS 10.15.2]
 - Python [e.g. Python 3.6]
 - Browser [e.g. Chrome 67 ]

**Additional context**

**Comment by renzhetiandi** [comment]
docker-compose 这个环境下载好之后，是不是需要指定https://github.com/Python3WebSpider/ProxyPool 这个链接啊，想了半天搞不明白，如果不把文件下载到本地电脑然后指定路径是怎么获取文件的呢，后来才了解到可以在docker-compose 这个环境里面配置，但是针对您这个项目，具体的步骤和哪些项需要配置，哪些不用动，还望大神指点，拜谢！！！小白一枚，还请多多关 V-V ，>_<

**Comment by renzhetiandi** [comment]
像我这样弱智的问题，您还是不用指点了，您还是直接在写个操作步骤吧，我俺您写的一步一步的操作
就不会错  哈哈

**Comment by renzhetiandi** [comment]
指点了怕是也会出错，也会有其他地方不懂

**Comment by Germey** [comment]
先代码下载下来：

```
git clone https://github.com/Python3WebSpider/ProxyPool.git
```

进入 ProxyPool 文件夹：

```
cd ProxyPool
```

运行 docker-compose up 命令：

```
docker-compose up
```

这样就好了。

**Comment by Germey** [comment]
就把代码下载下来：

```

```

**Comment by renzhetiandi** [comment]
非常感谢您能回复我，谢谢🙏大神



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 崔庆才丨静觅 ***@***.***&gt;
发送时间: 2021年6月1日 02:37
收件人: Python3WebSpider/ProxyPool ***@***.***&gt;
抄送: xiaoyang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Python3WebSpider/ProxyPool] docker只需要要一条命令，那里我卡住了，您是说的那个环境是只有把那两个下载好就可以，还是下载好还需要配置链接什么的，求大神帮助和理解一下小白吧， (#120)





 
Closed #120.
