### ISSUE TITLE
运行过程中会出现如下错误，求帮助解决

### ISSUE THREAD

**Issue by songzih** [Python3WebSpider/ProxyPool#122]
![c](https://user-images.githubusercontent.com/88181439/127612503-08f96304-0cff-497b-8d61-7a2e39072d90.png)

**Comment by zyj957** [comment]
兄弟，检查一下文件requirements.txt里面的插件是否都下载安装好了，最后启动docker再试一遍。

**Comment by ariesljm** [comment]
我也遇到了这个问题，
Complete output (3 lines):
    Building lxml version 4.6.3.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.

**Comment by ariesljm** [comment]
我试了下
docker 以前先在目录里面运行pip3 install -r requirements.txt，安装好依赖库，我估计是docker安装不了lxml导致的

**Comment by Germey** [comment]
现在已经修改成拉取我 build 好的镜像，可以重新试试。
