### ISSUE TITLE
docker启动出现问题

### ISSUE THREAD

**Issue by tt421011884** [Python3WebSpider/ProxyPool#127]
proxypool          | 2021-11-05 06:37:02.319 | INFO     | proxypool.processors.getter:run:36 - crawler <public.xiladaili.XiladailiCrawler object at 0x7f2df4901160> to get proxy
proxypool          | 2021-11-05 06:37:02.319 | INFO     | proxypool.crawlers.base:crawl:30 - fetching http://www.xiladaili.com/
proxypool          | 2021-11-05 06:37:02.320 | DEBUG    | proxypool.processors.tester:run:76 - 0 proxies to test
proxypool          | 2021-11-05 06:37:02.320 | DEBUG    | proxypool.processors.tester:run:79 - testing proxies use cursor 0, count 20
proxypool          | 2021-11-05 06:37:22.342 | DEBUG    | proxypool.scheduler:run_tester:32 - tester loop 18 start...
proxypool          | 2021-11-05 06:37:22.342 | INFO     | proxypool.processors.tester:run:74 - stating tester...
proxypool          | 2021-11-05 06:37:22.343 | DEBUG    | proxypool.processors.tester:run:76 - 0 proxies to test
proxypool          | 2021-11-05 06:37:22.343 | DEBUG    | proxypool.processors.tester:run:79 - testing proxies use cursor 0, count 20
proxypool          | 2021-11-05 06:37:36.345 | ERROR    | proxypool.processors.getter:run:37 - An error has been caught in function 'run', process 'MainProcess' (9), thread 'MainThread' (139835400836928):
proxypool          | Traceback (most recent call last):
proxypool          |
proxypool          |   File "run.py", line 12, in <module>
proxypool          |     getattr(Scheduler(), f'run_{args.processor}')()
proxypool          |             └ <class 'proxypool.scheduler.Scheduler'>
proxypool          |
proxypool          |   File "/app/proxypool/scheduler.py", line 48, in run_getter
proxypool          |     getter.run()
proxypool          |     │      └ <function Getter.run at 0x7f2df4c17730>
proxypool          |     └ <proxypool.processors.getter.Getter object at 0x7f2df48f55c0>
proxypool          |
proxypool          | > File "/app/proxypool/processors/getter.py", line 37, in run
proxypool          |     for proxy in crawler.crawl():
proxypool          |                  │       └ <function BaseCrawler.crawl at 0x7f2df570b950>
proxypool          |                  └ <public.xiladaili.XiladailiCrawler object at 0x7f2df4901160>
proxypool          |
proxypool          |   File "/app/proxypool/crawlers/base.py", line 31, in crawl
proxypool          |     html = self.fetch(url)
proxypool          |            │    │     └ 'http://www.xiladaili.com/'
proxypool          |            │    └ <function BaseCrawler.fetch at 0x7f2df570b8c8>
proxypool          |            └ <public.xiladaili.XiladailiCrawler object at 0x7f2df4901160>
proxypool          |
proxypool          |   File "/usr/local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
proxypool          |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
proxypool          |            │         │        │         │   │       └ {}
proxypool          |            │         │        │         │   └ (<public.xiladaili.XiladailiCrawler object at 0x7f2df4901160>, 'http://www.xiladaili.com/')
proxypool          |            │         │        │         └ <function BaseCrawler.fetch at 0x7f2df570b840>
proxypool          |            │         │        └ {'stop_max_attempt_number': 3, 'retry_on_result': <function BaseCrawler.<lambda> at 0x7f2df5708e18>, 'wait_fixed': 2000}
proxypool          |            │         └ ()
proxypool          |            └ <class 'retrying.Retrying'>
proxypool          |   File "/usr/local/lib/python3.6/site-packages/retrying.py", line 214, in call
proxypool          |     raise RetryError(attempt)
proxypool          |           │          └ Attempts: 3, Value: None
proxypool          |           └ <class 'retrying.RetryError'>
proxypool          |
proxypool          | retrying.RetryError: RetryError[Attempts: 3, Value: None]

**Comment by FourteenPro** [comment]
你好，解决了吗？我也遇到这个问题

**Comment by Germey** [comment]
你好，我更新了下代码，麻烦拉下最新代码或镜像再试试。

**Comment by Germey** [comment]
@FourteenPro 请试试好了吗？

**Comment by Germey** [comment]
暂时先关了，有问题再开～
