### ISSUE TITLE
docker compose up报错

### ISSUE THREAD

**Issue by hobbszhou** [Python3WebSpider/ProxyPool#128]
(1/27) Downgrading musl (1.1.24-r2 -> 1.1.18-r4)
(2/27) Downgrading zlib (1.2.11-r3 -> 1.2.11-r1)
(3/27) Installing libressl2.6-libcrypto (2.6.5-r0)
ERROR: libressl2.6-libcrypto-2.6.5-r0: trying to overwrite etc/ssl/cert.pem owned by ca-certificates-cacert-20191127-r1.
ERROR: libressl2.6-libcrypto-2.6.5-r0: trying to overwrite etc/ssl/openssl.cnf owned by libcrypto1.1-1.1.1g-r0.
(4/27) Installing libssh2 (1.9.0-r1)
(5/27) Installing libressl2.6-libssl (2.6.5-r0)
(6/27) Installing libcurl (7.61.1-r3)
(7/27) Installing curl (7.61.1-r3)
(8/27) Installing binutils-libs (2.30-r2)
(9/27) Installing binutils (2.30-r2)
(10/27) Installing gmp (6.1.2-r1)
(11/27) Installing isl (0.18-r0)
(12/27) Installing libgomp (6.4.0-r5)
(13/27) Installing libatomic (6.4.0-r5)
(14/27) Installing pkgconf (1.3.10-r0)
(15/27) Installing libgcc (6.4.0-r5)
(16/27) Installing mpfr3 (3.1.5-r1)
(17/27) Installing mpc1 (1.0.3-r1)
(18/27) Installing libstdc++ (6.4.0-r5)
(19/27) Installing gcc (6.4.0-r5)
(20/27) Installing zlib-dev (1.2.11-r1)
(21/27) Installing libxml2 (2.9.8-r1)
(22/27) Installing libxml2-dev (2.9.8-r1)
(23/27) Installing libgpg-error (1.27-r1)
(24/27) Installing libgcrypt (1.8.3-r2)
(25/27) Installing libxslt (1.1.31-r2)
(26/27) Installing libxslt-dev (1.1.31-r2)
(27/27) Installing musl-dev (1.1.18-r4)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
1 error; 113 MiB in 59 packages
The command '/bin/sh -c cat /etc/apk/repositories && echo -e http://mirrors.ustc.edu.cn/alpine/v3.7/main/ > /etc/apk/repositories && cat /etc/apk/repositories && apk update && apk add --no-cache libxml2-dev libxslt-dev gcc musl-dev curl ca-certificates && pip install -r requirements.txt && apk del gcc musl-dev libxml2-dev' returned a non-zero code: 1
ERROR: Service 'proxypool' failed to build : Build failed

**Comment by Germey** [comment]
你好，现在已经修改成拉取我已经 build 好的镜像，可以重新试试。
