### ISSUE TITLE
使用代理池的代理不成功

### ISSUE THREAD

**Issue by Lswx2017** [Python3WebSpider/ProxyPool#129]
使用代理池提供的代理，无法抓取。单独使用README里面的测试程序时，总是提示
ConnectionError : Max retries exceeded with url: (Caused by ProtocolError('Connection aborted. ', OSError(0, 'Error')))

**Comment by Germey** [comment]
这个代理池的代理就是不一定 100% 保证代理有效的，可以多重试。
