### ISSUE TITLE
README中错误的代码

### ISSUE THREAD

**Issue by XHG78999** [Python3WebSpider/ProxyPool#132]
**Describe the bug**
README示例中BASE_URL代码配置错误

**To Reproduce**
无

**Expected behavior**
无
**Screenshots**
![image](https://user-images.githubusercontent.com/53939187/147333007-71613165-872a-4655-bc05-2e1104a69216.png)

**Environments (please complete the following information):**
无

**Additional context**
拜托能不能加个单元测试。。。

**Comment by Germey** [comment]
哪错了？
