### ISSUE TITLE
运行docker-compose up 报File "/usr/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f。。。错误

### ISSUE THREAD

**Issue by FourteenPro** [Python3WebSpider/ProxyPool#133]
Digest: sha256:2e5cc182e18278b79a4db1196a393dc12594524bb3a231afbcfa934bde5816af
Status: Downloaded newer image for germey/proxypool:master
Creating proxypool       ... done
Creating redis4proxypool ... done
Attaching to redis4proxypool, proxypool
redis4proxypool    | 1:C 27 Dec 2021 12:39:54.264 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis4proxypool    | 1:C 27 Dec 2021 12:39:54.264 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis4proxypool    | 1:C 27 Dec 2021 12:39:54.264 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.266 * monotonic clock: POSIX clock_gettime
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.270 * Running mode=standalone, port=6379.
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.270 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.270 # Server initialized
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.271 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis4proxypool    | 1:M 27 Dec 2021 12:39:54.271 * Ready to accept connections
proxypool          | 2021-12-27 12:39:55,257 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
proxypool          | 2021-12-27 12:39:55,266 INFO supervisord started with pid 1
proxypool          | 2021-12-27 12:39:56,270 INFO spawned: 'getter' with pid 9
proxypool          | 2021-12-27 12:39:56,274 INFO spawned: 'server' with pid 10
proxypool          | 2021-12-27 12:39:56,291 INFO spawned: 'tester' with pid 11
proxypool          | 2021-12-27 12:39:57,296 INFO success: getter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool          | 2021-12-27 12:39:57,296 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool          | 2021-12-27 12:39:57,297 INFO success: tester entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool          |  * Serving Flask app "proxypool.processors.server" (lazy loading)
proxypool          |  * Environment: production
proxypool          |    WARNING: This is a development server. Do not use it in a production deployment.
proxypool          |    Use a production WSGI server instead.
proxypool          |  * Debug mode: off
proxypool          |  * Running on all addresses.
proxypool          |    WARNING: This is a development server. Do not use it in a production deployment.
proxypool          |  * Running on http://172.18.0.3:5555/ (Press CTRL+C to quit)
proxypool          | 2021-12-27 12:40:01.445 | DEBUG    | proxypool.scheduler:run_tester:32 - tester loop 0 start...
proxypool          | 2021-12-27 12:40:01.446 | INFO     | proxypool.processors.tester:run:74 - stating tester...
proxypool          | 2021-12-27 12:40:01.457 | DEBUG    | proxypool.processors.tester:run:76 - 0 proxies to test
proxypool          | 2021-12-27 12:40:01.458 | DEBUG    | proxypool.processors.tester:run:79 - testing proxies use cursor 0, count 20
proxypool          | Traceback (most recent call last):
proxypool          |   File "run.py", line 12, in <module>
proxypool          |     getattr(Scheduler(), f'run_{args.processor}')()
proxypool          |   File "/app/proxypool/scheduler.py", line 44, in run_getter
proxypool          |     getter = Getter()
proxypool          |   File "/app/proxypool/processors/getter.py", line 18, in __init__
proxypool          |     self.crawlers = [crawler_cls() for crawler_cls in self.crawlers_cls]
proxypool          |   File "/app/proxypool/processors/getter.py", line 18, in <listcomp>
proxypool          |     self.crawlers = [crawler_cls() for crawler_cls in self.crawlers_cls]
proxypool          |   File "/app/proxypool/crawlers/public/xiaoshudaili.py", line 19, in __init__
proxypool          |     html = self.fetch(url=BASE_URL)
proxypool          |   File "/usr/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
proxypool          |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
proxypool          |   File "/usr/lib/python3.6/site-packages/retrying.py", line 214, in call
proxypool          |     raise RetryError(attempt)
proxypool          | retrying.RetryError: RetryError[Attempts: 3, Value: None]
proxypool          | 2021-12-27 12:40:20,582 INFO exited: getter (exit status 1; not expected)
proxypool          | 2021-12-27 12:40:21.473 | DEBUG    | proxypool.scheduler:run_tester:32 - tester loop 1 start...
proxypool          | 2021-12-27 12:40:21.474 | INFO     | proxypool.processors.tester:run:74 - stating tester...
proxypool          | 2021-12-27 12:40:21,477 INFO spawned: 'getter' with pid 18
proxypool          | 2021-12-27 12:40:21.479 | DEBUG    | proxypool.processors.tester:run:76 - 0 proxies to test
proxypool          | 2021-12-27 12:40:21.479 | DEBUG    | proxypool.processors.tester:run:79 - testing proxies use cursor 0, count 20
proxypool          | 2021-12-27 12:40:22,485 INFO success: getter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool          | 2021-12-27 12:40:41.504 | DEBUG    | proxypool.scheduler:run_tester:32 - tester loop 2 start...
proxypool          | 2021-12-27 12:40:41.504 | INFO     | proxypool.processors.tester:run:74 - stating tester...
proxypool          | 2021-12-27 12:40:41.506 | DEBUG    | proxypool.processors.tester:run:76 - 0 proxies to test
proxypool          | 2021-12-27 12:40:41.506 | DEBUG    | proxypool.processors.tester:run:79 - testing proxies use cursor 0, count 20
proxypool          | Traceback (most recent call last):
proxypool          |   File "run.py", line 12, in <module>
proxypool          |     getattr(Scheduler(), f'run_{args.processor}')()
proxypool          |   File "/app/proxypool/scheduler.py", line 44, in run_getter
proxypool          |     getter = Getter()
proxypool          |   File "/app/proxypool/processors/getter.py", line 18, in __init__
proxypool          |     self.crawlers = [crawler_cls() for crawler_cls in self.crawlers_cls]
proxypool          |   File "/app/proxypool/processors/getter.py", line 18, in <listcomp>
proxypool          |     self.crawlers = [crawler_cls() for crawler_cls in self.crawlers_cls]
proxypool          |   File "/app/proxypool/crawlers/public/xiaoshudaili.py", line 19, in __init__
proxypool          |     html = self.fetch(url=BASE_URL)
proxypool          |   File "/usr/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
proxypool          |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
proxypool          |   File "/usr/lib/python3.6/site-packages/retrying.py", line 214, in call
proxypool          |     raise RetryError(attempt)
proxypool          | retrying.RetryError: RetryError[Attempts: 3, Value: None]

**Comment by FourteenPro** [comment]
这个是因为在docker镜像中安装的retrying出错导致导致的吗？删除拉取的镜像和容器。重新运行docker-compose up也没有解决

**Comment by FourteenPro** [comment]
我的运行环境实在centos7.5

**Comment by Germey** [comment]
我感觉是不是你本身网络环境出现了问题，我如果把机器断网，和你出现的效果是一样的。

**Comment by Germey** [comment]
你好，我更新了下代码，麻烦拉下最新代码或镜像再试试。

**Comment by Germey** [comment]
先关啦哈～ 应该解决了
