### ISSUE TITLE
无效ip没有验证 无法访问 也不会删除

### ISSUE THREAD

**Issue by vvvtz** [Python3WebSpider/ProxyPool#134]
运行了两分钟 http://localhost:5555/count 就6000多数据了
全是无效的 一直运行 也不见减少 说明没有验证ip  也不会删除不对的ip 下载下来没有改过
是我运行方式不对还是咋回事

**Comment by Germey** [comment]
一开始爬取到的代理会设置10分，需要验证10次一直失败才会移除，所以不会那么快就删除的哈。有效的代理都是100分，ramdom接口会优先取100分的代理返回。

**Comment by vvvtz** [comment]
怎么查看100分的代理数量 取的代理能只取https不

**Comment by vvvtz** [comment]
想改成获取就检测一次不成功就删除ip 需要改哪里

**Comment by Germey** [comment]
`查看可用的也就是100分或者最高分的代理数量` 这块没有开放接口出来，你可以自行实现一个接口暴露出来，参考 https://github.com/Python3WebSpider/ProxyPool/blob/642a59571621788d4a7fef7218b05a8a2694fd3a/proxypool/storages/redis.py#L111 这边的实现即可。
`代理可以加上http https分开取吗`目前这个不支持的。
