### ISSUE TITLE
k8s环境下配置读取redis环境变量错误

### ISSUE THREAD

**Issue by staugur** [Python3WebSpider/ProxyPool#136]
**Describe the bug**
在k8s环境中，服务自动发现机制，会给pod设置环境变量，假设我有个名为`redis`的服务，那么pod中会有下列环境变量：

```ini
REDIS_PORT_6379_TCP_PORT=6379
REDIS_PORT=tcp://10.43.131.181:6379
REDIS_SERVICE_PORT_REDIS=6379
REDIS_SERVICE_HOST=10.43.131.181
REDIS_SERVICE_PORT=6379
REDIS_PORT_6379_TCP=tcp://10.43.131.181:6379
REDIS_PORT_6379_TCP_ADDR=10.43.131.181
REDIS_PORT_6379_TCP_PROTO=tcp
```

在这种情况下部署 ProxyPool，会乱的：

```bash
environs.EnvValidationError: Environment variable "REDIS_PORT" invalid: Not a valid integer.
```

**Expected behavior**

**Environments (please complete the following information):**
 - k3s v1.21 + containerd 1.4
 - Python 3.7

**Suggestions**

环境变量拥有自己的特别前缀。

ps：解析 redis url 何不采用 [from_url](https://redis-py.readthedocs.io/en/stable/connections.html#redis.client.Redis.from_url) 函数呢？
缺少 PASSWORD PORT 貌似现在的解析函数都会有正则错误，
把 `REDIS_` 相关变量去掉，或者内部封装一个解析函数，把 `REDIS_` 系列转化为 `URL` 形式，应该也不错。

**Comment by Germey** [comment]
感谢建议，我之前 K8s 中确实也遇到了 `REDIS_PORT `，后来 env 覆盖了这个变量解决了该问题，后来没有再优化，环境变量拥有自己的特别前缀是一个好的建议，我试着修复一下。

解析 URL 那块之前写过一个方法就直接用了，的确 form_url 是不错的选择，我试着优化下。

**Comment by staugur** [comment]
对了，Flask正式环境运行（APP_ENV=prod）好像还是 `app.run` 开发模式，正式环境一般用gunicorn、uWsgi之类，有待增强。

**Comment by staugur** [comment]
嗯~ 要不晚点我提pr吧
Working 🥲

**Comment by Germey** [comment]
https://github.com/Python3WebSpider/ProxyPool/issues/136#issuecomment-1002883790 对于这个已经提了 PR 了：https://github.com/Python3WebSpider/ProxyPool/pull/137

**Comment by Germey** [comment]
https://github.com/Python3WebSpider/ProxyPool/issues/136#issuecomment-1002887633 感谢，这块当时就从简做了，如果可以的话，麻烦您提一个 PR 优化吧，谢谢～

**Comment by staugur** [comment]
> 嗯~ 要不晚点我提pr吧 Working 

#138 在py内部启动app，可以试试这几种小众方式，不过貌似大众方式是gunicorn、uwsgi之类的外部启动。
