### ISSUE TITLE
本地调试Flask会出现双进程

### ISSUE THREAD

**Issue by vmomo** [Python3WebSpider/ProxyPool#140]
崔老师好，
本地调试偶尔flask会出现双进程，造成前端卡死的状态
将server.py下的

`if IS_DEV:
app.debug=Ture
`
注释掉后这个现象就不出现了

PS.刚刚入门也可能是环境设置的问题，解决的方法也简单粗暴了

**Comment by Germey** [comment]
测试了下似乎没复现，这个是只在开发阶段出现吗？只运行不会出现这种情况。

**Comment by vmomo** [comment]
是的，在开发过程中出现，查了一些问题后可能是自动重新加载引起的，设置app.debug=False后就不会出现了。
我多检查几遍自己的代码，很有可能是初学者犯得低级错误
顺便感谢你的系列教程，营养丰富好吸收  :)

**Comment by Germey** [comment]
多谢～

**Comment by inVains** [comment]
确实是flask dev模式下reload了。
实际上造成tester,getter都在运行两次了。
private getter请求代理时，如果代理api有请求频率限制，就有问题了。

两个处理方案：

1. 设置环境变量，proxypool运行于非dev模式。`export APP_ENV=prod`
2. 建议代码修改scheduler.py->run_server-> app.run()，增加`use_reloader=False`参数。应该在proxypool项目里，flask server的配置文件修改，需要重新加载的情况不多吧。

![image](https://github.com/Python3WebSpider/ProxyPool/assets/2282229/f046022a-7e7b-4395-8932-23720cd1a2ad)

https://stackoverflow.com/questions/25504149/why-does-running-the-flask-dev-server-run-itself-twice
