### ISSUE TITLE
redis服务器不妨设成仅本地/docker内部可访问

### ISSUE THREAD

**Issue by hyf3513OneGO** [Python3WebSpider/ProxyPool#143]
redis服务器默认启动时不设置密码，而且在compose file中将宿主机的6374端口直接转发到redis容器的6379端口，可能会导致redis容器被入侵。
或许可以通过在compose.yml中设置network，并在代理池程序中通过容器名的方式来连接redis容器，以提高安全性

**Comment by Germey** [comment]
的确，make sense，宿主机如果不设限的话，会存在这种问题，我找时间修复下这个问题，感谢您的建议～

**Comment by Germey** [comment]
感谢建议，我发现我只需要移除 ports 相关配置就好了，如果有需要可以手动打开，应该不需要配置单独 network，已经更新。
