### ISSUE TITLE
似乎无法关闭debug日志

### ISSUE THREAD

**Issue by thank243** [Python3WebSpider/ProxyPool#145]
开启了prod后，debug日志依然输出。查看setting.py有对loguru相关设置，但是只影响error.log文件。实际还是会打印debug。这样会导致日志文件过大。

**Comment by thank243** [comment]
setting.py添加如下可以解决
```python3
import sys

logger.remove()
logger.add(sys.stderr, level='ERROR')
```

**Comment by Germey** [comment]
谢谢提醒，我找时间修复下。

**Comment by Germey** [comment]
https://github.com/Python3WebSpider/ProxyPool/pull/146

Fixed
