### ISSUE TITLE
Requirements内package问题

### ISSUE THREAD

**Issue by 42Viva** [Python3WebSpider/ProxyPool#147]
Requirements.txt内的meinheld包貌似不支持window，无法安装运行

> C:\Users\DELL>pip install meinheld
Looking in indexes: https://pypi.douban.com/simple/
Collecting meinheld
  Downloading https://pypi.doubanio.com/packages/a6/41/f11e4dbfe35f251b1fe10cee5b186a4ac29de3e03fede010db40313d829e/meinheld-1.0.2.tar.gz (83 kB)
     ---------------------------------------- 83.1/83.1 KB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
│ exit code: 1
  ╰─> [2 lines of output]
      Are you really running a posix compliant OS ?
      Be posix compliant is mandatory
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Germey** [comment]
你好，这个如果不用 meinheld 启动的话可以不用这个包。或者尝试试试 Docker 的吧
