### ISSUE TITLE
拉取最新镜像，无法启动

### ISSUE THREAD

**Issue by hotpeppeper** [Python3WebSpider/ProxyPool#148]
**Describe the bug**
拉取最新镜像，无法启动，试了3次，每次都是一样的问题
redis4proxypool    | 1:C 16 Mar 2022 01:58:15.820 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis4proxypool    | 1:C 16 Mar 2022 01:58:15.821 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis4proxypool    | 1:C 16 Mar 2022 01:58:15.821 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.821 * monotonic clock: POSIX clock_gettime
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.822 * Running mode=standalone, port=6379.
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.822 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.822 # Server initialized
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.822 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis4proxypool    | 1:M 16 Mar 2022 01:58:15.822 * Ready to accept connections
proxypool          | 2022-03-16 01:58:16,106 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
proxypool          | 2022-03-16 01:58:16,108 INFO RPC interface 'supervisor' initialized
proxypool          | 2022-03-16 01:58:16,109 CRIT Server 'unix_http_server' running without any HTTP authentication checking
proxypool          | 2022-03-16 01:58:16,109 INFO supervisord started with pid 1
proxypool          | 2022-03-16 01:58:17,111 INFO spawned: 'getter' with pid 10
proxypool          | 2022-03-16 01:58:17,111 INFO spawned: 'server' with pid 11
proxypool          | 2022-03-16 01:58:17,112 INFO spawned: 'tester' with pid 12
proxypool          | Traceback (most recent call last):
proxypool          |   File "run.py", line 1, in <module>
proxypool          |     from proxypool.scheduler import Scheduler
proxypool          |   File "/app/proxypool/scheduler.py", line 3, in <module>
proxypool          |     from proxypool.processors.server import app
proxypool          |   File "/app/proxypool/processors/server.py", line 1, in <module>
proxypool          |     from flask import Flask, g
proxypool          |   File "/root/.local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
proxypool          |     from jinja2 import escape
proxypool          |   File "/root/.local/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
proxypool          |     from .environment import Environment
proxypool          |   File "/root/.local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
proxypool          |     from .defaults import BLOCK_END_STRING
proxypool          |   File "/root/.local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
proxypool          |     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
proxypool          |   File "/root/.local/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
proxypool          |     from markupsafe import soft_unicode
proxypool          | ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.local/lib/python3.7/site-packages/markupsafe/__init__.py)

**Environments (please complete the following information):**
 - OS: ubuntu 16.04

**Comment by aliQWQ** [comment]
一样 我也是

**Comment by sketts** [comment]
> 一样，我也是。我使用的doker方法。 ` ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.local/lib/python3.7/site-packages/markupsafe/init.py)`

docker 拉取的 jinja2 包有问题，下载 jinja2 3.0.3 替换镜像里面的包，就可以。

**Comment by staugur** [comment]
与 jinja2 本身版本似乎关系不大，是依赖的 MarkupSafe 2.1.X版本的问题，换成低版本可以：
`pip install 'MarkupSafe<2.1.0'`

**Comment by Germey** [comment]
已经修复
