### ISSUE TITLE
运行getter任务时，如果遇到某个网站超时，报错会直接终止getter任务

### ISSUE THREAD

**Issue by requireCool** [Python3WebSpider/ProxyPool#150]
## 问题描述

我这里的网络环境在获取第一个66ip.cn的代理的时候就会遇到超时ReadTimeout错误，然后整个getter任务就终止了，导致代理池里始终一个代理都没有，希望可以在遇到报错后跳过，去抓取下一个代理商

## 截图信息

下图可以看到，getter运行了5轮，tester运行了37轮，池里仍然没有代理
![image](https://user-images.githubusercontent.com/55184050/160982471-38e0c8e7-238d-4570-b492-c273456d417e.png)

遇到的超时报错
![image](https://user-images.githubusercontent.com/55184050/160982523-38411736-3167-4988-ab12-f06cd5c4d251.png)

**Comment by Germey** [comment]
![image](https://user-images.githubusercontent.com/8678661/161995509-65f6be23-7cc0-4c55-b825-993b62187fb2.png)

感谢反馈，我刚测试了下是能跳过的。

之前会有这个问题，能否尝试下拉下最新镜像看看。

```
docker pull germey/proxypool:master
```

**Comment by requireCool** [comment]
刚才重新拉了镜像，不存在这个问题了

我看上次镜像是14天前的，但是这个问题发现于6天前，可能是拉到了缓存导致的，如果其他同学遇到了类似问题可以在拉镜像的时候指定最新日期的tag，而不是master或latest

**Comment by HT944** [comment]
我是用你的源码构建的镜像，这个新版的还没构建，不知道有没有问题
