### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by onewtfboy** [Python3WebSpider/ProxyPool#152]
请问在抓取模块中，base.py文件中的基类并未定义parse函数，并且parse函数是定义在了子类中，为何在基类的process函数中直接调用了parse函数？
![image](https://user-images.githubusercontent.com/102864017/161385893-ce6084af-2b83-45e3-97c6-df4309c09ef4.png)

**Comment by Germey** [comment]
因为子类对父类有继承，实际运行的时候都是运行的子类对象，所以能找到 process、parse 等方法。
