### ISSUE TITLE
本地运行不起来，麻烦看看报错？

### ISSUE THREAD

**Issue by phoenixor** [Python3WebSpider/ProxyPool#157]
本地环境：win10 64位，python 3.10.2
百度过，防火墙都是关闭的
![image](https://user-images.githubusercontent.com/6568115/166616119-7295de54-065d-4f4f-91aa-2b6a78b89896.png)
![image](https://user-images.githubusercontent.com/6568115/166616134-5f35e687-7a5e-47d4-89e8-78a344531aad.png)

**Comment by y2000zhang** [comment]
您好，我已收到您的邮件，我将尽快给您回复。Hello, I have received your email, I will reply to you as soon as possible.
