### ISSUE TITLE
requirements.txt中的 redis版本有限制

### ISSUE THREAD

**Issue by SZFsir** [Python3WebSpider/ProxyPool#16]
requirements.txt中redis版本为redis>=2.10.5
默认会安装最新版，现在已经3.x了。
试验证明，操作zadd时会报错。

**Comment by daimengxiaozhi** [comment]
怎么解决的 ？？

**Comment by daimengxiaozhi** [comment]
我是直接改的 源代码 ，zadd 方法变了 第二个参数 是字典  {proxy:score}

**Comment by blackyao** [comment]
> 只要卸掉重新安装redis2.10.5就可以了

怎么安装？

**Comment by SZFsir** [comment]
pip安装啊

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
