### ISSUE TITLE
请问如何让本地浏览器走代理池动态返回的代理呢？

### ISSUE THREAD

**Issue by xiangqunXiao** [Python3WebSpider/ProxyPool#160]
sorry，刚学，想在本地浏览器打开网页时（就手动打开正常浏览网页的场景），走返回的代理池代理。
请问有比较简单的解决方案吗

**Comment by cyicz123** [comment]
感觉没有比较方便的解决方案，因为这些拿到的代理都是可用性较差的代理。

**Comment by Germey** [comment]
个人不太推荐这样做，可用性不高。
