### ISSUE TITLE
关于redis4proxypool的问题

### ISSUE THREAD

**Issue by hourku** [Python3WebSpider/ProxyPool#168]
在docker-compose.yml中，redis4proxypool没有设置开机自启，导致每次重启需要手动开启redis4proxypool，不设置redis4proxypool自启是有什么考虑吗？

**Comment by Germey** [comment]
docker-compose 只是为了方便测试而设置的，对开机自启什么的没有什么考虑支持。如果要正式部署的话还是建议比如 Kubernetes，设置对应策略来自启。
