### ISSUE TITLE
测试了下 不支持https  但现在网站基本都是https的 

### ISSUE THREAD

**Issue by hilbp** [Python3WebSpider/ProxyPool#171]

**Comment by Blackhatfrance** [comment]
Nobody fix that ?

**Comment by lycanthropes** [comment]
确实,现在网站都是https的,这个脚本获取的代理ip没有用

**Comment by Germey** [comment]
HTTPS 网站也可以用 HTTP 代理来爬取。

设置的时候：

proxies = {
   'http': 'http://<proxy>',
   'https': 'http://<proxy>'
}
