### ISSUE TITLE
关于redis单独测试的问题

### ISSUE THREAD

**Issue by flowercoder** [Python3WebSpider/ProxyPool#172]
直接运行redis.py中的main，会出现如下错误。
'module' object has no attribute 'StrictRedis
解决方式：
重命名redis.py，将它重命名成非redis.py的名字
参考:https://blog.csdn.net/qq_41663800/article/details/88084414.。
麻烦将这个问题close，让遇到类似的问题的，可以看此参考。

**Comment by Germey** [comment]
多谢！
