### ISSUE TITLE
mac 上使用 docker 部署出错。

### ISSUE THREAD

**Issue by huyixi** [Python3WebSpider/ProxyPool#196]
➜  ProxyPool: docker-compose up
[+] Running 0/1
 ⠇ proxypool Pulling                                                       5.9s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by y2000zhang** [comment]
您好，我已收到您的邮件，我将尽快给您回复。Hello, I have received your email, I will reply to you as soon as possible.

**Comment by savioryu** [comment]
可以试一试，在 docker-compose.yml 中，给 proxypool 增加配置 platform: linux/amd64。

![image](https://github.com/Python3WebSpider/ProxyPool/assets/4270438/4e0ef29b-66db-46a3-b162-8da38bb799d7)

**Comment by huyixi** [comment]
已解决
