### ISSUE TITLE
请问能仅修改docker-compose.yml和接口模块来配置针对多个网站分别获取代理吗

### ISSUE THREAD

**Issue by x0chaoren0s** [Python3WebSpider/ProxyPool#216]
我只会flask，所以只能改接口模块。。

我希望能实现类似这样的内容：

@app.route('/random')
def get_proxy():
    """
    获取随机可用代理
    :return: 随机代理
    """
    # 如访问http://127.0.0.1:5555/random?websitehost=site1.com 就返回针对site1.com的代理
    # 如访问http://127.0.0.1:5555/random?websitehost=site2.org 就返回针对site2.org的代理
    websitehost= request.args.get('websitehost')   
    conn = magic_get_conn(websitehost)
    return conn.random()

**Comment by Germey** [comment]
目前暂未加这个支持，现在是一个通用的代理池。
