### ISSUE TITLE
what/

### ISSUE THREAD

**Issue by 1019wellBegin121** [Python3WebSpider/ProxyPool#23]
D:\Pycharm工作资料\代码流\venv\Scripts\python.exe C:/Users/ThinkPad/Downloads/ProxyPool-master/run.py
浠ｇ悊姹犲紑濮嬭繍琛�
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
Process Process-2:
寮�濮嬫姄鍙栦唬鐞�
鑾峰彇鍣ㄥ紑濮嬫墽琛�
Crawling http://www.66ip.cn/1.html
姝ｅ湪鎶撳彇 http://www.66ip.cn/1.html
鎶撳彇鎴愬姛 http://www.66ip.cn/1.html 200
鎴愬姛鑾峰彇鍒颁唬鐞� 177.185.148.46:58623
鎴愬姛鑾峰彇鍒颁唬鐞� 131.196.143.11:7
鎴愬姛鑾峰彇鍒颁唬鐞� 131.196.143.117:33729
鎴愬姛鑾峰彇鍒颁唬鐞� 43.243.141.126:53281
鎴愬姛鑾峰彇鍒颁唬鐞� 111.181.35.219:9999
Crawling http://www.66ip.cn/2.html
姝ｅ湪鎶撳彇 http://www.66ip.cn/2.html
鎶撳彇鎴愬姛 http://www.66ip.cn/2.html 200
鎴愬姛鑾峰彇鍒颁唬鐞� 170.0.112.226:50359
鎴愬姛鑾峰彇鍒颁唬鐞� 54.39.144.247:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 171.41.82.36:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 37.32.126.0:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 213.33.224.82:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 144.123.71.133:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 111.177.166.59:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 117.196.237.40:59250
鎴愬姛鑾峰彇鍒颁唬鐞� 121.61.3.110:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 212.200.126.14:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 47.107.245.9:4
鎴愬姛鑾峰彇鍒颁唬鐞� 47.107.245.94:3128
Crawling http://www.66ip.cn/3.html
姝ｅ湪鎶撳彇 http://www.66ip.cn/3.html
鎶撳彇鎴愬姛 http://www.66ip.cn/3.html 200
鎴愬姛鑾峰彇鍒颁唬鐞� 111.177.162.175:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 110.52.235.60:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 37.224.19.1:0
鎴愬姛鑾峰彇鍒颁唬鐞� 175.100.185.151:53281
鎴愬姛鑾峰彇鍒颁唬鐞� 37.224.19.10:6
鎴愬姛鑾峰彇鍒颁唬鐞� 179.127.249.5:3
鎴愬姛鑾峰彇鍒颁唬鐞� 37.224.19.106:58553
鎴愬姛鑾峰彇鍒颁唬鐞� 179.127.249.53:46257
鎴愬姛鑾峰彇鍒颁唬鐞� 111.177.183.4:5
鎴愬姛鑾峰彇鍒颁唬鐞� 1.20.101.221:55707
鎴愬姛鑾峰彇鍒颁唬鐞� 111.177.183.45:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 91.219.171.8:4
Crawling http://www.66ip.cn/4.html
姝ｅ湪鎶撳彇 http://www.66ip.cn/4.html
鎶撳彇鎴愬姛 http://www.66ip.cn/4.html 200
鎴愬姛鑾峰彇鍒颁唬鐞� 91.219.171.84:43726
鎴愬姛鑾峰彇鍒颁唬鐞� 212.26.247.178:38418
鎴愬姛鑾峰彇鍒颁唬鐞� 203.42.227.1:1
鎴愬姛鑾峰彇鍒颁唬鐞� 203.42.227.11:3
鎴愬姛鑾峰彇鍒颁唬鐞� 203.42.227.113:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 110.52.235.126:9999
鎴愬姛鑾峰彇鍒颁唬鐞� 170.239.224.58:8080
鎴愬姛鑾峰彇鍒颁唬鐞� 190.119.199.18:57333
鎴愬姛鑾峰彇鍒颁唬鐞� 5.0.0.815:0
鎴愬姛鑾峰彇鍒颁唬鐞� 190.152.182.150:53281
鎴愬姛鑾峰彇鍒颁唬鐞� 119.40.98.84:46119
鎴愬姛鑾峰彇鍒颁唬鐞� 111.177.170.220:9999
Traceback (most recent call last):
  File "D:\python\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\python\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ThinkPad\Downloads\ProxyPool-master\proxypool\scheduler.py", line 28, in schedule_getter
    getter.run()
  File "C:\Users\ThinkPad\Downloads\ProxyPool-master\proxypool\getter.py", line 30, in run
    self.redis.add(proxy)
  File "C:\Users\ThinkPad\Downloads\ProxyPool-master\proxypool\db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\_compat.py", line 122, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'

**Comment by gary101** [comment]
我也遇到这个问题，还没解决，求解

**Comment by Dongxuxiang1994** [comment]
崔的代码有错，元类那边有点错误，我修改了下，不过爬取的网站比较少https://github.com/Dongxuxiang1994/ProxyPool/tree/master/ProxyPool

**Comment by freshcoder2018** [comment]
应该是redis版本导致的问题，最简单的方法就是把redis版本恢复到2.10.5

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
