### ISSUE TITLE
在使用的过程中出出现  AttributeError: 'int' object has no attribute 'items'

### ISSUE THREAD

**Issue by Duchongc** [Python3WebSpider/ProxyPool#25]
![image](https://user-images.githubusercontent.com/31360737/53712942-f1cea380-3e83-11e9-8d8c-4995bdc912ed.png)

**Comment by 371524zhouha** [comment]
我也碰到这个问题 不知道怎么解决，请问你解决了没有?

**Comment by Duchongc** [comment]
我感觉是爬的东西有问题，就是有脏数据啦，导致items没分出来，可以先从这入手，我还没解决，期待崔老师临幸，哈哈(ಡωಡ)hiahiahia发自我的华为手机-------- 原始邮件 --------主题：Re: [Python3WebSpider/ProxyPool] 在使用的过程中出出现  AttributeError: 'int' object has no attribute 'items' (#25)发件人：371524zhouha 收件人：Python3WebSpider/ProxyPool 抄送：521anran <1978529954@qq.com>,Author 我也碰到这个问题 不知道怎么解决，请问你解决了没有?

**Comment by 371524zhouha** [comment]
嗯嗯  谢谢 期待大佬来解决一下

**Comment by Scrat250** [comment]
> 嗯嗯 谢谢 期待大佬来解决一下

试试：pip install redis==2.10.6

**Comment by 0209HMQNSKYD** [comment]
有大佬解决了的麻烦说一下

**Comment by 371524zhouha** [comment]
可以了 真心感谢。谢谢。

**Comment by 0209HMQNSKYD** [comment]
能说一下怎么解决的吗

**Comment by 371524zhouha** [comment]
我的电脑是      在cmd命令窗口 输入pip3 install redis==2.10.6    就是更新一下redis的版本，之后就没有出现上述的问题了

**Comment by 0209HMQNSKYD** [comment]
安装了，可是不知道在哪启动

**Comment by Duchongc** [comment]
发自我的华为手机好的，感谢，我尝试一下-------- 原始邮件 --------主题：Re: [Python3WebSpider/ProxyPool] 在使用的过程中出出现  AttributeError: 'int' object has no attribute 'items' (#25)发件人：371524zhouha 收件人：Python3WebSpider/ProxyPool 抄送：521anran <1978529954@qq.com>,Author 我的电脑是      在cmd命令窗口 输入pip3 install redis==2.10.6    就是更新一下redis的版本，之后就没有出现上述的问题了

**Comment by 371524zhouha** [comment]
启动  参考下载页https://github.com/Python3WebSpider/ProxyPool  下边的说明啊  cmd进入LianJiaSpider-master目录 然后输入python run.py

**Comment by 0209HMQNSKYD** [comment]
我想问的是启动redis，不过现在已解决。谢谢

**Comment by triangle959** [comment]
把requirement里的改为redis==2.10.6，然后再run就可以了

**Comment by hfengshan** [comment]
这个问题是由于redis.zadd 方法不正确导致的，return self.db.zadd(REDIS_KEY, score,proxy)修改为return self.db.zadd(REDIS_KEY, {proxy:score}) 就可以解决问题了。

**Comment by Duchongc** [comment]
收到，谢谢回复发自我的华为手机-------- 原始邮件 --------主题：Re: [Python3WebSpider/ProxyPool] 在使用的过程中出出现  AttributeError: 'int' object has no attribute 'items' (#25)发件人：hfengshan 收件人：Python3WebSpider/ProxyPool 抄送：521anran <1978529954@qq.com>,Author 这个问题是由于redis.zadd 方法不正确导致的，return self.db.zadd(REDIS_KEY, score,proxy)修改为return self.db.zadd(REDIS_KEY, {proxy:score}) 就可以解决问题了。

**Comment by lp8608** [comment]
解决方案：
pip3 install redis==2.10.6

**Comment by zouzhin** [comment]
redis版本升级了的问题。
两处问题，都已经有人解答过。
1、zadd(REDIS_KEY, {proxy:score}) 第二个参数要为字典类型
2、zincrby(REDIS_KEY, -1,proxy ) 参数要交换顺序

**Comment by Betterming** [comment]
我的win10 解决方案是，修改proxypool文件夹下的db文件，第30行 return self.db.zadd(REDIS_KEY, score, proxy)为return self.db.zadd(REDIS_KEY,{proxy:score})

**Comment by Miles-sudo** [comment]
根据博客https://blog.csdn.net/mygodit/article/details/86689127提供的方法
修改db.py中的30行,78行
源代码:return self.db.zadd(REDIS_KEY, MAX_SCORE, proxy)
改为:return self.db.zadd(REDIS_KEY, {proxy: MAX_SCORE})
db.py中的57行
源代码:return self.db.zincrby(REDIS_KEY, proxy, -1)
改为:return self.db.zincrby(REDIS_KEY, -1, proxy)
