### ISSUE TITLE
新版redis中zadd改动

### ISSUE THREAD

**Issue by canglan1024** [Python3WebSpider/ProxyPool#27]
新的版本中zadd有改动，需要改成zadd(REDIS_KEY, {proxy: score})
一共两处，分别在RedisClient.add()和RedisClient.max()里

**Comment by mirrortan** [comment]
新版的 `zincrby()` 函数也有更新，需要改成  `zincrby(REDIS_KEY, -1, proxy)`，更新位置一处：RedisClient.decrease()。

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
