### ISSUE TITLE
爬虫函数可以考虑增加一个直接读文件

### ISSUE THREAD

**Issue by zouzhin** [Python3WebSpider/ProxyPool#28]
粗略写了个，放在Crawler类里面，每行用“地址：端口”格式就行。
    def crawl_file(self):
        filename = 'proxy.txt'  # txt文件和当前脚本在同一目录下，所以不用写具体路径
        with open(filename, 'r') as file_to_read:
            while True:
                lines = file_to_read.readline()  # 整行读取数据
                if not lines:
                    break
                yield lines

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！

上述问题我调整为了 Class 架构
