### ISSUE TITLE
是否存在管理redis connectionpool的问题？

### ISSUE THREAD

**Issue by XyLearningProgramming** [Python3WebSpider/ProxyPool#30]
https://stackoverflow.com/questions/31663288/how-do-i-properly-use-connection-pools-in-redis
我在想每次请求链接redis都创建一个链接，不如写成
`redis_pool = None

class RedisClient(object):
    def __init__(self, host=HOST, port=PORT):
        global redis_pool

        if not redis_pool:
            if PASSWORD:
                redis_pool = redis.Redis(host=host, port=port, password=PASSWORD)
            else:
                redis_pool = redis.Redis(host=host, port=port)
            self._db = redis_pool
        else:
            self._db = redis_pool`

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！

支持了 REDIS_CONNECTION_STRING
