### ISSUE TITLE
嗯把大神的直接拿过来运行，一开始还能运行，爬着爬着报错了，好难啊，感觉好复杂

### ISSUE THREAD

**Issue by FlyingDreamFish** [Python3WebSpider/ProxyPool#31]
代理池开始运行
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
开始抓取代理
获取器开始执行
Crawling http://www.66ip.cn/1.html
正在抓取 http://www.66ip.cn/1.html
抓取成功 http://www.66ip.cn/1.html 521
Crawling http://www.66ip.cn/2.html
正在抓取 http://www.66ip.cn/2.html
抓取成功 http://www.66ip.cn/2.html 521
Crawling http://www.66ip.cn/3.html
正在抓取 http://www.66ip.cn/3.html
抓取成功 http://www.66ip.cn/3.html 521
Crawling http://www.66ip.cn/4.html
正在抓取 http://www.66ip.cn/4.html
抓取成功 http://www.66ip.cn/4.html 521
正在抓取 http://www.ip3366.net/?stype=1&page=1
抓取成功 http://www.ip3366.net/?stype=1&page=1 200
成功获取到代理 222.135.25.243:8060
成功获取到代理 180.175.8.5:8060
成功获取到代理 119.180.131.25:8060
成功获取到代理 180.175.160.130:8060
成功获取到代理 119.180.177.138:8060
成功获取到代理 119.180.1.42:8060
成功获取到代理 171.112.165.22:9999
成功获取到代理 222.182.121.71:8118
成功获取到代理 118.81.68.2:80
成功获取到代理 117.166.3.51:8118
正在抓取 http://www.ip3366.net/?stype=1&page=2
抓取成功 http://www.ip3366.net/?stype=1&page=2 200
成功获取到代理 171.83.164.51:9999
成功获取到代理 47.101.189.13:80
成功获取到代理 171.112.164.149:9999
成功获取到代理 171.112.164.109:9999
成功获取到代理 119.97.237.74:80
成功获取到代理 197.234.42.73:8083
成功获取到代理 103.120.152.182:59068
成功获取到代理 117.168.86.102:8118
成功获取到代理 115.215.212.116:8118
成功获取到代理 103.244.91.61:8080
正在抓取 http://www.ip3366.net/?stype=1&page=3
抓取成功 http://www.ip3366.net/?stype=1&page=3 200
成功获取到代理 117.80.137.238:9999
成功获取到代理 103.233.145.133:8080
成功获取到代理 117.80.17.81:8118
成功获取到代理 171.83.165.10:9999
成功获取到代理 43.248.123.237:8080
成功获取到代理 113.227.182.15:8118
成功获取到代理 138.97.219.51:65301
成功获取到代理 117.41.142.159:8118
成功获取到代理 197.234.42.209:8083
成功获取到代理 197.234.44.125:8083
Process Process-2:
Traceback (most recent call last):
  File "D:\Python\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Python\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\spider-test\ProxyPool-master\proxypool\scheduler.py", line 28, in schedule_getter
    getter.run()
  File "D:\spider-test\ProxyPool-master\proxypool\getter.py", line 30, in run
    self.redis.add(proxy)
  File "D:\spider-test\ProxyPool-master\proxypool\db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "D:\Python\lib\site-packages\redis\client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "D:\Python\lib\site-packages\redis\_compat.py", line 109, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'

**Comment by FlyingDreamFish** [comment]
下面有解决方法，看到了，打扰了

**Comment by zxbzxb180** [comment]
请问一下，你是直接导入项目运行run.py吗？？我这样运行到打开了API就卡住了，程序停止但也不往下走。

**Comment by dingdapang** [comment]
> 下面有解决方法，看到了，打扰了

你怎么解决的啊 我和你一样的问题

**Comment by Bagabaga007** [comment]
> 
> 
> 下面有解决方法，看到了，打扰了

怎么解决？0.0

**Comment by wuhuaxingyu** [comment]
> > 下面有解决方法，看到了，打扰了
> 
> 怎么解决？0.0

下面有zadd的改动的问题，你看一下

**Comment by weidongzhou1994** [comment]
求问各位大神，出现下述错误怎么处理？：
![image](https://user-images.githubusercontent.com/40510496/64399778-54effb80-d09c-11e9-9ceb-866b7c406e31.png)

**Comment by weidongzhou1994** [comment]
一直卡在 代理请求失败 121.232.148.91:9000

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
