### ISSUE TITLE
crawl_ip3366（）函数是不是有一个多余了，源代码中并没有删除或注释

### ISSUE THREAD

**Issue by Chauncey2** [Python3WebSpider/ProxyPool#32]
Crawl.py模块里是不是有个函数写多余了，crawl_ip3366写了两个。

**Comment by Anodsaber** [comment]
这两个函数重名了，分别抓的是同一个网站的首页ip和免费页ip。留一个就行

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
