### ISSUE TITLE
大佬们，为什么我运行run.py之后就没反应了

### ISSUE THREAD

**Issue by zxbzxb180** [Python3WebSpider/ProxyPool#34]
程序也不报错，也不停止，但就是什么也不显示，那些print的语句我写了的。
![1](https://user-images.githubusercontent.com/50437772/57691109-dea33580-7675-11e9-98a0-8985ee29c4cb.png)

**Comment by zxbzxb180** [comment]
@Germey 老师可以帮忙解决一下嘛，现在显示一句代理池开始运行，接着显示API运行的信息，然后就不显示东西了，一直停在这里

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
