### ISSUE TITLE
关于trace back中db.py的问题

### ISSUE THREAD

**Issue by Wade-D** [Python3WebSpider/ProxyPool#35]
看了之前的issues都说要把db.py中的add和max两个函数里的zadd方法的参数修改成字典形式（zadd(REDIS_KEY, {proxy：score})），以及decrease函数里的zincrby方法参数对调（zincrby(REDIS_KEY, -1， proxy)）但是我修改之后反而会出问题。
我去看了Redis-py的文档，不知道是不是有什么改版，发现作者原本写的才符合文档里的要求。
文档说明如下：
![image](https://user-images.githubusercontent.com/50258701/57928488-75c0f500-78e3-11e9-98c4-27826d76c4c7.png)
![image](https://user-images.githubusercontent.com/50258701/57928455-62158e80-78e3-11e9-9cf5-b19d449b13ed.png)

所以这两个地方其实不用改了。
不过有个地方似乎是错了，
![image](https://user-images.githubusercontent.com/50258701/57928538-9be69500-78e3-11e9-8386-97977e9f1618.png)
，框住的第一个应该是MIN_SCORE吧？

**Comment by KayFelicities** [comment]
你看的应该是老版的文档，最新的已经改过了，如果用最新的redis-py库在运行时会报错的。
另外你说的似乎错了的地方其实是对的，意思是取出最高分的代理。
