### ISSUE TITLE
运行run后卡在“获取器开始执行”

### ISSUE THREAD

**Issue by irwenjust** [Python3WebSpider/ProxyPool#4]
相关配置和安装等都搞定了，之前那个用pop实现的也能用，但这个我运行run后却卡在“获取器开始执行”，请问怎么解决？谢谢了。

**Comment by cowry5** [comment]
我是改了redis的keys就能正常运行了

**Comment by changjiale** [comment]
if TESTER_ENABLED:
            tester_process = Process(target=self.schedule_tester)
            tester_process.start()
        
        if GETTER_ENABLED:
            getter_process = Process(target=self.schedule_getter)
            getter_process.start()
        
        if API_ENABLED:
            api_process = Process(target=self.schedule_api)
            api_process.start()

我这只执行第一个为true的东西   不是我想想的交替执行

**Comment by AStupid** [comment]
是不是没开redis服务器

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
