### ISSUE TITLE
在 VS Code 中运行异常 ~ 而且无法关闭

### ISSUE THREAD

**Issue by mirrortan** [Python3WebSpider/ProxyPool#44]
当在命令行中运行 `python run.py` 时，项目可以正常工作，可以通过 <http://127.0.0.1:5555/random> 获取到代理；但当使用 VS Code 直接运行（按 <kbd>F5</kbd>）时，会出现异常，而且关不掉，几次都是自己通过重启才关掉。

有大佬能解释一下么？

**Comment by DEPAPEPE1412** [comment]
遇到同样的问题，使用VS Code按F5运行就会出异常，电脑突然巨卡，关不掉，只能重启，但是点击右上角的运行按钮却可以正常运行。

**Comment by HIT-Owen** [comment]
> 当在命令行中运行 `python run.py` 时，项目可以正常工作，可以通过 http://127.0.0.1:5555/random 获取到代理；但当使用 VS Code 直接运行（按 F5）时，会出现异常，而且关不掉，几次都是自己通过重启才关掉。
> 
> 有大佬能解释一下么？

应该是跟flask服务有关系, f5是debug模式, 如果要debug可以将API_ENABLED设置为False

**Comment by Germey** [comment]
新版本修改了一些架构和 Bug，欢迎试用和提宝贵意见，谢谢！
以上问题应该不会出现了。
