### ISSUE TITLE
AttributeError: 'OutStream' object has no attribute 'buffer'

### ISSUE THREAD

**Issue by Heguanlin-rec** [Python3WebSpider/ProxyPool#48]
#启动代理池

from proxypool.scheduler import Scheduler
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def main():
    try:
        s = Scheduler()
        s.run()
    except:
        main()

if __name__ == '__main__':
    main()

AttributeError: 'OutStream' object has no attribute 'buffer'

**Comment by Eleven-is-cool** [comment]
我也是哇

**Comment by Germey** [comment]
新版本修改了一些架构和 Bug，欢迎试用和提宝贵意见，谢谢！
