### ISSUE TITLE
redis的有序集合zadd方法变更

### ISSUE THREAD

**Issue by cxapython** [Python3WebSpider/ProxyPool#49]
def add(self, proxy, score=INITIAL_SCORE):
        """
        添加代理，设置分数为最高
        :param proxy: 代理
        :param score: 分数
        :return: 添加结果
        """
        if not re.match('\d+\.\d+\.\d+\.\d+\:\d+', proxy):
            print('代理不符合规范', proxy, '丢弃')
            return
        if not self.db.zscore(REDIS_KEY, proxy):
            dic={}
            dic[proxy] =score

            return self.db.zadd(REDIS_KEY, dic)

**Comment by weidongzhou1994** [comment]
在哪里更改啊？只用更改db 文件吗？

**Comment by cxapython** [comment]
> 在哪里更改啊？只用更改db 文件吗？

凡是使用了zadd方法的都要改，因为api变了。

**Comment by DEPAPEPE1412** [comment]
谢谢提醒，改了这个就没有报错了

**Comment by DEPAPEPE1412** [comment]
> ```
> def add(self, proxy, score=INITIAL_SCORE):
>     """
>     添加代理，设置分数为最高
>     :param proxy: 代理
>     :param score: 分数
>     :return: 添加结果
>     """
>     if not re.match('\d+\.\d+\.\d+\.\d+\:\d+', proxy):
>         print('代理不符合规范', proxy, '丢弃')
>         return
>     if not self.db.zscore(REDIS_KEY, proxy):
>         dic={}
>         dic[proxy] =score
> 
>         return self.db.zadd(REDIS_KEY, dic)
> ```

谢谢提醒，改了这个就没有报错了

**Comment by Germey** [comment]
新版本修改了一些架构和 Bug，欢迎试用和提宝贵意见，谢谢！
