### ISSUE TITLE
代码看起来太费劲了，必须完全按照你书上来，才走的通

### ISSUE THREAD

**Issue by zxcwolf** [Python3WebSpider/ProxyPool#50]
代码看起来太费劲了，必须完全按照你书上来，才走的通，我又不想安装redis

**Comment by Anodsaber** [comment]
按照书上的走一遍就能理解了

**Comment by HIT-Owen** [comment]
里面难点是元类还有协程 异步IO,  这个只能自己看了, 其他的部分跟着书前面学过来应该问题不大

**Comment by Germey** [comment]
新版本修改了一些架构和 Bug，欢迎试用和提宝贵意见，谢谢！

**Comment by zxcwolf** [comment]
你好，我用selenium 有些网站打不开。比如下面这个。正常在浏览器中是可以打开的，是什么原因呢？ 似乎是跳转的问题。请问如何修改代码能打开呢？


from selenium import webdriver
driver= webdriver.Chrome()
driver.get("http://mobile.nmpa.gov.cn/datasearch/QueryList?tableId=26&searchF=Quick%20SearchK&pageIndex=1&pageSize=15")















在 2020-02-20 00:49:18，"崔庆才丨静觅" <notifications@github.com> 写道：

新版本修改了一些架构和 Bug，欢迎试用和提宝贵意见，谢谢！
