### ISSUE TITLE
代理获取进程好像死亡了，这是怎么回事

### ISSUE THREAD

**Issue by yanw1011** [Python3WebSpider/ProxyPool#55]
运行过程中代理抓取进程好像死亡了，不知道是什么问题？
观察到测试进程和API进程一直在运行，代理抓取进程没有动，redis队列中代理也一直在减少，有人知道这是什么问题吗？

**Comment by kengsley1993** [comment]
Try to reduce some of the crawl_ function in crawler.py and test is it work first.
In my case, if I set the TARGET_URL to some special url, my webrowser dont able to get in localhost:5555 somehow. 
But I am sure that the program is working fine at all.
