### ISSUE TITLE
代码中url错误导致的retrying.RetryError: RetryError[Attempts: 3, Value: None]

### ISSUE THREAD

**Issue by samzhuoyiran** [Python3WebSpider/ProxyPool#57]
**url错误导致的retrying模块报错问题**
* proxypool.crawlers.daili66.BASE_URL:http://www.664ip.cn/{page}.html ,这个url的域名应该是写错了，改成 www.66ip.cn 就可以正常运行

**Comment by samzhuoyiran** [comment]
已提交PR

**Comment by Germey** [comment]
Thanks，这里当时为了测试报错改了下，忘记改回来了，非常感谢！
