### ISSUE TITLE
程序执行不成功

### ISSUE THREAD

**Issue by darksheng** [Python3WebSpider/ProxyPool#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22118981/75881778-b7169700-5e5a-11ea-89d0-e87b7bb4e252.png)

**Environments (please complete the following information):**
 - OS: [win10]
 - Python [Python 3.7]

**Additional context**

**Comment by darksheng** [comment]
ImportError: cannot import name '__all__' from 'proxypool.crawlers'

**Comment by Germey** [comment]
你好，我这边测试了下，并不能复现出现有问题。代码中 https://github.com/Python3WebSpider/ProxyPool/blob/3ed5a8ab3896ef7905176d028cb050124529000c/proxypool/crawlers/__init__.py#L14 这里是定义了 `__all__` 这个变量的。

请确认下是否是最新的 master 分支的 code，或者可以用 Docker 启动。

如还有问题，请再留言给我，谢谢。

**Comment by darksheng** [comment]
谢谢，下载最新的解决了，书写的很全，但是重新出现了问题。当我执行getter程序的时候，
![image](https://user-images.githubusercontent.com/22118981/76140665-d1898400-6097-11ea-8d93-929ba0e4c304.png)
当我执行redis.py这个程序的时候，'__version__'这个属性应该是存在的，但是报错了。
![image](https://user-images.githubusercontent.com/22118981/76140683-ed8d2580-6097-11ea-9102-0ba74d69e312.png) 感谢回答

**Comment by Germey** [comment]
明白了，你用的 redis Python 库是 redis 3.x 吧。确实是我的问题，当时是在 redis 2.x 测试的，3.x 的 proxy 这边我忘记修改为 string 类型了，可以把 `proxy` 修改为 `proxy.string()`，也可以把 redis Python 包降级为 2.x，如 requirements.txt 里所写。

**Comment by Germey** [comment]
我做了一下修改，现在应该也能直接运行了。
如果还有问题请再留言，谢谢你的支持。

**Comment by darksheng** [comment]
成功运行，感谢

**Comment by Germey** [comment]
好嘞，那我 Issue 关闭了哈~
