### ISSUE TITLE
我访问localhost:5555/random时 不能换代理 多次刷新只有一个最初的代理地址，请问一下是什么问题？

### ISSUE THREAD

**Issue by wendy60** [Python3WebSpider/ProxyPool#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. macOS 10.15.2]
 - Python [e.g. Python 3.6]
 - Browser [e.g. Chrome 67 ]

**Additional context**

**Comment by Germey** [comment]
看看你的 redis 里面 100 分的代理有多少呢？
