### ISSUE TITLE
老哥，多加几个代理源吧，现在一次只能抓十个有用的了。

### ISSUE THREAD

**Issue by shenbushou** [Python3WebSpider/ProxyPool#64]
不知为啥，机子只能跑你的代码不出错。。。。。拜托！！！

**Comment by Germey** [comment]
公开的代理就是不太行，你可以购买付费的，然后对接到 private 部分

**Comment by Germey** [comment]
报错信息可以发下嘛？

**Comment by shenbushou** [comment]
1.你的代码有一处
2020-05-16 13:33:38.775 | ERROR    | proxypool.processors.getter:run:36 - An error has been caught in function 'run', process 'Process-2' (35620), thread 'MainThread' (35744):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 428
               │     └ 3
               └ <function _main at 0x0000023058F02820>
  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 428
           │    └ <function BaseProcess._bootstrap at 0x0000023058CFEE50>
           └ <Process name='Process-2' parent=35140 started>
  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x0000023058CFE4C0>
    └ <Process name='Process-2' parent=35140 started>
  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-2' parent=35140 started>
    │    │        │    └ ()
    │    │        └ <Process name='Process-2' parent=35140 started>
    │    └ <bound method Scheduler.run_getter of <proxypool.scheduler.Scheduler object at 0x0000023058F15BE0>>
    └ <Process name='Process-2' parent=35140 started>

  File "C:\Users\tony\Desktop\ProxyPool-master\proxypool\scheduler.py", line 48, in run_getter
    getter.run()
    │      └ <function Getter.run at 0x000002305A0CF1F0>
    └ <proxypool.processors.getter.Getter object at 0x0000023058C97730>

> File "C:\Users\tony\Desktop\ProxyPool-master\proxypool\processors\getter.py", line 36, in run
    for proxy in crawler.crawl():
        │        │       └ <function BaseCrawler.crawl at 0x000002305A0CAEE0>
        │        └ <public.kuaidaili.KuaidailiCrawler object at 0x000002305A693190>
        └ Proxy(host='114.104.138.156', port='9999')

  File "C:\Users\tony\Desktop\ProxyPool-master\proxypool\crawlers\base.py", line 25, in crawl
    html = self.fetch(url)
    │      │    │     └ 'https://www.kuaidaili.com/free/inha/2/'
    │      │    └ <function BaseCrawler.fetch at 0x000002305A0CAE50>
    │      └ <public.kuaidaili.KuaidailiCrawler object at 0x000002305A693190>
    └ '<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n<meta http-equiv="Content-Type" co...

  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
           │         │        │         │   │       └ {}
           │         │        │         │   └ (<public.kuaidaili.KuaidailiCrawler object at 0x000002305A693190>, 'https://www.kuaidaili.com/free/inha/2/')
           │         │        │         └ <function BaseCrawler.fetch at 0x000002305A0CADC0>
           │         │        └ {'stop_max_attempt_number': 3, 'retry_on_result': <function BaseCrawler.<lambda> at 0x0000023059FDCE50>}
           │         └ ()
           └ <class 'retrying.Retrying'>
  File "C:\Users\tony\AppData\Local\Programs\Python\Python38\lib\site-packages\retrying.py", line 214, in call
    raise RetryError(attempt)
          │          └ Attempts: 3, Value: None
          └ <class 'retrying.RetryError'>

retrying.RetryError: RetryError[Attempts: 3, Value: None]



2.在运行这个代理池时https://github.com/jhao104/proxy_pool。没有报错，127.0.0.1可以打开。但是访问随机获取代理的地址：http://127.0.0.1:5010/get。显示127.0.0.1拒绝访问。
以上

**Comment by shenbushou** [comment]
> 公开的代理就是不太行，你可以购买付费的，然后对接到 private 部分

我拿来刷seo的，虽然买的ip才0.04元一个，，，但是失去乐趣了。

**Comment by shenbushou** [comment]
老哥，拜托加几个代理源吧，，，我试了十几个代理池了，除了抓取部分有用，其他的各种错误。就你的主程序最稳定。这么好的框架，只放了三四个代理源可惜了。我把seo的部分开给你。百度引擎刷关键词排名非常高效。

**Comment by Germey** [comment]
行的行的，可以提供一点代理源吗？麻烦列一下，我对接进去

**Comment by RVVAAI** [comment]
> 行的行的，可以提供一点代理源吗？麻烦列一下，我对接进去

http://www.data5u.com/ ,https://www.xicidaili.com/wn/

**Comment by shenbushou** [comment]
平时用的都在这了。几个太差的没加进去
每个站点随机取五个ip测试，每个ip测试一次

1.站大爷：https://www.zdaye.com/dayProxy.html前两篇文章里，几乎都可用，质量高
2.无忧代理：http://www.data5u.com/首页更新20个，响应比较慢，但基本可用。
3.西刺代理：http://www.xicidaili.com首页更新，质量参差不齐
4.全球免费代理IP库：https://ip.jiangxianli.com/首页更新，在存活内的一般可用
5.ip海http://www.iphai.com/首页更新，有可用
6.齐代理：http://www.qydaili.com/free/?action更新时间顺序很乱，一个可用
7.西拉代理：www.xiladaili.com首页更新，存活时间内有可用
8.89代理：http://www.89ip.cn/index_1.html更新量较大，未发现可用
9.Ip3366：http://www.ip3366.net/首页更新10个，未发现可用
10.全网代理：http://www.goubanjia.com/首页更新 ，未发现可用
以上2020.5.19晚21：00-22：00测试

**Comment by shenbushou** [comment]
平时用的基本上都在这了，几个太差的没加进去
每个站点随机取五个ip测试，每个ip测试一次

1.站大爷：https://www.zdaye.com/dayProxy.html前两篇文章里，几乎都可用，质量高
2.无忧代理：http://www.data5u.com/首页更新20个，响应比较慢，但基本可用。
3.西刺代理：http://www.xicidaili.com首页更新，质量参差不齐
4.全球免费代理IP库：https://ip.jiangxianli.com/首页更新，在存活时间内的一般可用
5.ip海http://www.iphai.com/首页更新，有可用
6.齐代理：http://www.qydaili.com/free/?action更新时间顺序很乱，一个可用
7.西拉代理：www.xiladaili.com首页更新，存活时间内有可用
8.89代理：http://www.89ip.cn/index_1.html更新量较大，未发现可用
9.Ip3366：http://www.ip3366.net/首页更新10个，未发现可用
10.全网代理：http://www.goubanjia.com/首页更新 ，未发现可用。
以上2020.5.19晚21.00-22.00测试

**Comment by shenbushou** [comment]
平时用的基本上都在这了，几个太差的没加进去
每个站点随机取五个ip测试，每个ip测试一次

1.站大爷：https ://www.zdaye.com/dayProxy.html 前两篇文章里，几乎都可用，质量高
2.无忧代理：http : //www.data5u.com/ 首页更新20个，响应比较慢，但基本可用。
3.西刺代理：http://www.xicidaili.com首页更新，质量参差不齐
4.全球免费代理IP库：https://ip.jiangxianli.com/首页更新，在存活期间的一般可用
5.ip海http://www.iphai.com/首页更新，有可用
6.齐代理：http : //www.qydaili.com/free/?action更新时间顺序很乱，一个可用
7.西拉代理：www.xiladaili.com首页更新，在存活期间的有可用
8.9代理：http : //www.89ip.cn/index_1.html更新量过多，未发现可用
9.ip3366：http ://www.ip3366.net/ 首页更新10个，未发现可用
10.全网代理：http : //www.goubanjia.com/首页更新，未发现可用
2020.5.19晚21.00- 22.00测试

**Comment by RiskySignal** [comment]
我遇到了和@shenbushou 一样的问题，经过一阵调试以后，我发现是因为国外ip无法访问的缘故，尝试一下关闭翻墙软件，再运行脚本试试，希望有用。

另外，这个工具实在是太棒了！！

**Comment by Germey** [comment]
老哥们，我刚加了 data5u 和 xici，其他的大家有空能否仿照加一下啊？

**Comment by shenbushou** [comment]
加个站大爷都可以了，这里有个正则表达式逻辑可以借鉴，   站大爷代理：http://ip.zdaye.com/dayProxy.html
        """
        url = 'http://ip.zdaye.com/dayProxy.html'
        html = requests(url)
        sttrs = re.findall('<H3 class="title"><a href="(.*?)">', html, re.S)
        for sttr in sttrs:
            new_url = url[:28] + sttr[9:]
            new_html = requests_other(new_url)
            get_div = re.search("<div class=\"cont\">(.*?)</div>", new_html, re.S).group(1)
            print(get_div)
            results = re.findall("<br>(.*?)@(.*?)#\[(.*?)\]", get_div, re.S)

**Comment by Germey** [comment]
@shenbushou 能发个 pull request 吗？

**Comment by shenbushou** [comment]
不会玩 pull request 。。。。。

**Comment by shenbushou** [comment]
seo软件，输入代理接口和要刷的网址，设定时间，自动建立局部代理刷新。链接: https://pan.baidu.com/s/1oR66QuzmA16cSXAoLIWCNg 提取码: 7758

**Comment by Germey** [comment]
> seo软件，输入代理接口和要刷的网址，设定时间，自动建立局部代理刷新。链接: https://pan.baidu.com/s/1oR66QuzmA16cSXAoLIWCNg 提取码: 7758

你这是打广告吗？

**Comment by jwdeaa** [comment]
just a new proxy list.

http://pzzqz.com/

**Comment by Germey** [comment]
@jwdeaa 老哥方便贡献 PR 吗？

**Comment by XHG78999** [comment]
我按照书里写了个类似的，可以看看。 https://github.com/XHG78999/Proxypool
