### ISSUE TITLE
能否在控制台稳定地关闭代理池

### ISSUE THREAD

**Issue by EMUNES** [Python3WebSpider/ProxyPool#65]
作者的主程序很稳定，试了几个只有这个代理池最好。但我使用时有碰到了一个不太方便的地方，由于我打算让我的我的爬虫定时间断采集，所以希望ip池也能够定时完成采集更新等服务。所以我尝试在py文件内使用subprocess.Popen调用代理池，即运行run.py（三个服务都启动），可以成功，但是却无法利用Popen对象的terminate或者kill方法使它停止：
```
def shut_proxy_pool(p):
    p.terminate()

p = start_proxy_pool()
time.sleep(5)
# 作者README md中的同样方法
proxy = get_random_proxy()
print(proxy)
shut_proxy_pool(p)
```
我使用的是windows 10， vscode + python 3.82，同样我在控制台内输入命令也不行，只有退出控制台才可以。但是这样我的vscode偶尔会产生卡死的情况，出于时间因素我没有研究源码，所以请问有什么方法可以中止程序的运行吗，谢谢作者！

**Comment by Germey** [comment]
你好，抱歉上次没注意到这个 issue，回复晚了。

首先这个代理池的设计就不是为了随时中断的，建议代理池一直运行着，API 一直开着，代理通过 API 随用随取，如果想要尽可能实时采集那可以把更新时间缩短一点，CYCLE_GETTER 设置短一点就好了。

另外代理池也设置了 KeyBoardInterrupt 事件监听，[https://github.com/Python3WebSpider/ProxyPool/blob/master/proxypool/scheduler.py#L83](https://github.com/Python3WebSpider/ProxyPool/blob/master/proxypool/scheduler.py#L83) 可以看下，所以你要这么做的话，可以模拟键盘事件发送 SIGINT 事件试下。
