### ISSUE TITLE
请问这个是什么错误啊？

### ISSUE THREAD

**Issue by ryanwlb** [Python3WebSpider/ProxyPool#70]
![image](https://user-images.githubusercontent.com/16047642/84873286-972b7c00-b0b5-11ea-9a82-7c6eeb5f4cff.png)
![image](https://user-images.githubusercontent.com/16047642/84873326-a7dbf200-b0b5-11ea-9631-9e491d5727fe.png)

Redis确认了地址和端口以及密码没错误

**Comment by WanBuJin** [comment]
不能看你的图片
