### ISSUE TITLE
请问下用scrapy.request，如果调用代理，用meta带入proxy参数，不能使用

### ISSUE THREAD

**Issue by WanBuJin** [Python3WebSpider/ProxyPool#71]
import requests
import scrapy
from scrapy.http import Request

proxypool_url = 'http://127.0.0.1:5555/random'
target_url = 'https://www.zw3e.com/zwdq/'

def get_random_proxy():
    """
    get random proxy from proxypool
    :return: proxy
    """
    return requests.get(proxypool_url).text.strip()

def crawl(url, proxy):
    """
    use proxy to crawl page
    :param url: page url
    :param proxy: proxy, such as 8.8.8.8:8888
    :return: html
    """
    # proxy = 'http://' + proxy
    yield scrapy.Request(url, callback=parse,**meta={'proxy':proxy}**)
    # response.encoding = 'utf-8'
    # return response.text

def parse(response):
    print(response)

def main():
    """
    main method, entry point
    :return: none
    """
    proxy = get_random_proxy()
    print('get random proxy', proxy)
    crawl(target_url, proxy)
    # print(html)

if __name__ == '__main__':
    main()

**Comment by Germey** [comment]
是代理本身的问题，有些代理就是不太稳定或者速度很慢，可以多次重试。
