### ISSUE TITLE
检测模块有误？？？？

### ISSUE THREAD

**Issue by zzh5687** [Python3WebSpider/ProxyPool#73]
检测模块，我发现一个严重bug，也不应该说是bug，应该是有序集合的特性，不知道只有我还是？？python版本3.8.1   python redis版本3.4.1    redis版本4.0.9    。情况如下：我第一次启动检测模块，结束后发现有好多ip的分数还是10，我感到很奇怪，于是我开始第二次启动检测模块，结束后还是有好多ip分数是10，有些ip分数还减到了4，5，6,发现是因为有些IP重复被检测。这时我大悟，想到有序集合的顺序是按照分数排的，你分批次检测ip每次检测每次分数都变每次都重新排序，所以导致有些ip检测不到分数一直是10，但是为什么有些IP重复被检测导致分数减到4，5，6....没想明白。

**Comment by winturn** [comment]
假如有100个代理（a0-a99），每次取20个，每个代理初始都是10分。
为了方便描述，简单描述该有序集合为[a0-a19,a20-a39,a40-a59,a60-a79,a80-a99]
第一次取第0-20个（a0-a19），然后都减一。那么这20个代理就变成了9分。
这时有序集合的排序是[a20-a39,a40-a59,a60-a79,a80-a99,a0-a19]
然后第二次取第20-40个（因为有序集合是按分值大小排序，实际上取到的是a40-a59），然后减一，那么这20个代理就变成了9分。
这时有序集合的排序是[a20-a39,a60-a79,a80-a99,a0-a19,a40-a59]
然后第三次取第40-60个（a80-a99），然后减1。那么这20个代理就变成了9分。
排序变成[a20-a39,a60-a79,a0-a19,a40-a59,a80-a99]
然后第四次取第60-80个（a40-a59）,然后减1。因为这几个代理在第二次取数时已经被减了1分变成了9分，现在这次减分，把这些变成了8分。
排序变成[a20-a39,a60-a79,a0-a19,a80-a99,a40-a59]
然后第五次取第80-100个（a40-a59）,然后减1。这些数第三次被减分，现在变成了7分。
所以，这样一次下来之后，变成了
a20-a39：10分
a60-a79：10分
a0-a19：9分
a80-a99：9分
a40-a59：7分

**Comment by Germey** [comment]
@zzh5687 是的  @winturn 的解释是没问题的，的确存在这样的问题。

感谢 @winturn 的贡献，我会尽快测试并 merge。

**Comment by Germey** [comment]
merged https://github.com/Python3WebSpider/ProxyPool/pull/78
