### ISSUE TITLE
利用docker部署时，执行docker-compose up后，会下载很多东西，而且速度特别慢，这个能解答下么，本人纯小白，在docker方面。

### ISSUE THREAD

**Issue by chenjieup** [Python3WebSpider/ProxyPool#87]

**Comment by Germey** [comment]
就是会下载很多镜像，你可以设置加速镜像，搜索 `Docker pull 加速`相关关键字了解下。

**Comment by cnscorpions** [comment]
@chenjieup 你可以修改下Dockerfile文件，`RUN pip install -r requirements.txt -i https://pypi.douban.com/simple`使用国内源即可
@Germey  可以在readme提示下

**Comment by Germey** [comment]
@cnscorpions 感谢提醒，已经加上了
