### ISSUE TITLE
docker部署的时候出现Exception~~~

### ISSUE THREAD

**Issue by chenjieup** [Python3WebSpider/ProxyPool#88]
![image](https://user-images.githubusercontent.com/29012810/91321668-74be8900-e7f1-11ea-9ae3-f5d20da3d00e.png)
![image](https://user-images.githubusercontent.com/29012810/91321741-8738c280-e7f1-11ea-8b70-e1084e06a06e.png)

**Comment by Germey** [comment]
再试几次吧，网络问题。

**Comment by chenjieup** [comment]
试了几次，还不行。我可不可以手动去下载？

**Comment by Germey** [comment]
或者直接改下源码把，比如 Dockerfile 里面，加上 pypi 源

**Comment by Germey** [comment]
https://github.com/Python3WebSpider/ProxyPool/blob/master/Dockerfile#L4

改成 

```
pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
```
