### ISSUE TITLE
关于可配置项中部分配置的疑问

### ISSUE THREAD

**Issue by Hui4401** [Python3WebSpider/ProxyPool#90]
大佬，能问下 setting.py 中的环境配置项 **APP_ENV** 和 **APP_DEBUG** 影响的是哪部分的环境么，我无论修改还是删除那一部分代码对程序都没有任何影响，并且 server 部分永远是 production 环境，如果是控制 flask 环境，不应该是 **FLASK_ENV** 和 **FLASK_DEBUG** 么？

**Comment by Germey** [comment]
尴尬呀，我应该在 https://github.com/Python3WebSpider/ProxyPool/blob/master/proxypool/scheduler.py#L59 这个地方加上 APP_DEBUG  的判定的，忘记加了。

**Comment by Germey** [comment]
或者您还有什么建议吗？

**Comment by Hui4401** [comment]
果然是这样，不过要控制 debug 开关的话，设置环境变量 FLASK_ENV 的值（development，production）就可以办到，也就不用额外的代码判断了。
