### ISSUE TITLE
docker-compose up 启动失败

### ISSUE THREAD

**Issue by pythonName** [Python3WebSpider/ProxyPool#97]
**Describe the bug**
修改docker-compose.yml文件如下：
version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: always
  proxypool:
    build: .
    image: 'germey/proxypool'
    container_name: proxypool
    ports:
      - "5555:5555"
    restart: always
    volumes:
      - /tmp/proxypool/crawlers/private:/app123/proxypool/crawlers/private
    environment:
      APP_ENV: prod
      REDIS_HOST: 6.189.119.212
      API_PORT: 3520
      API_HOST: 6.189.119.212
      TEST_URL: https://zh.savefrom.net/7/
      REDIS_PORT: 6371
      REDIS_PASSWORD: redis88812

然后执行docker-compose up
Creating network "proxypool_default" with the default driver
Creating proxypool ... done
Creating redis     ... done
Attaching to proxypool, redis
redis        | 1:C 07 Oct 2020 11:58:47.833 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis        | 1:C 07 Oct 2020 11:58:47.833 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis        | 1:C 07 Oct 2020 11:58:47.833 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis        | 1:M 07 Oct 2020 11:58:47.834 * Running mode=standalone, port=6379.
redis        | 1:M 07 Oct 2020 11:58:47.834 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis        | 1:M 07 Oct 2020 11:58:47.834 # Server initialized
redis        | 1:M 07 Oct 2020 11:58:47.835 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis        | 1:M 07 Oct 2020 11:58:47.835 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
redis        | 1:M 07 Oct 2020 11:58:47.835 * Ready to accept connections
proxypool    | 2020-10-07 11:58:48,129 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
proxypool    | 2020-10-07 11:58:48,134 INFO supervisord started with pid 1
proxypool    | 2020-10-07 11:58:49,137 INFO spawned: 'getter' with pid 7
proxypool    | 2020-10-07 11:58:49,140 INFO spawned: 'server' with pid 8
proxypool    | 2020-10-07 11:58:49,143 INFO spawned: 'tester' with pid 9
proxypool    | 2020-10-07 11:58:50,153 INFO success: getter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool    | 2020-10-07 11:58:50,153 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool    | 2020-10-07 11:58:50,153 INFO success: tester entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxypool    | 2020-10-07 11:58:50,441 INFO exited: server (exit status 1; not expected)
proxypool    | 2020-10-07 11:58:51,445 INFO spawned: 'server' with pid 19
proxypool    | 2020-10-07 11:58:52,259 INFO exited: server (exit status 1; not expected)
proxypool    | 2020-10-07 11:58:53,271 INFO spawned: 'server' with pid 23
proxypool    | 2020-10-07 11:58:54,053 INFO exited: server (exit status 1; not expected)
proxypool    | 2020-10-07 11:58:56,059 INFO spawned: 'server' with pid 27
proxypool    | 2020-10-07 11:58:56,789 INFO exited: server (exit status 1; not expected)
proxypool    | 2020-10-07 11:58:59,794 INFO spawned: 'server' with pid 31
proxypool    | 2020-10-07 11:59:00,522 INFO exited: server (exit status 1; not expected)
proxypool    | 2020-10-07 11:59:01,523 INFO gave up: server entered FATAL state, too many start retries too quickly

总是报错，代理服务总是无法访问，新手，望指教！

**Comment by Germey** [comment]
比较诡异的问题，相关输出也看不出是什么问题。请提供下：
* 操作系统类型
* 操作系统版本
* Docker 版本

**Comment by pythonName** [comment]
**Docker version:**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

**操作系统类型：【64位】**
CentOS Linux release 7.8.2003 (Core)

**Comment by pythonName** [comment]
第一次干净的环境按你的步骤是成功了的，后面我添加了docker-compose.yml里面的环境变量，然后重新docker-compose up就出现这样的问题了，另外我不修改docker-compose.yml，指教修改proxypool/setting.py里面的相关配置，然后docker-compose up也报这个错。

我感觉是不是第一次运行产生的镜像或是容器没有删掉，导致后面每次重新运行都是用的之前的镜像或是容器

**Comment by Germey** [comment]
现在已经修改成运行我已经 build 好的镜像，请重新试试。
